display:
  name: Hello ${project.name}
project:
  name: "Banner project"
spring:
  application:
    name: banner-project
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/banner_campaign_db}
#    url: jdbc:postgresql://localhost:15432/banner_campaign_db
#    url: jdbc:postgresql://192.168.89.100:5432/banner_campaign_db
#    username: ${SPRING_DATASOURCE_USER:martinv}
#    password: ${SPRING_DATASOURCE_PASSWORD:Password123@}
    username: ${SPRING_DATASOURCE_USER:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    #    username: postgres
#    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default-schema: banner_campaign
        show_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
    default-schema: banner_campaign

## Logging
#  logging:
#    file:
#      name: ${LOG_FILE_PATH:/opt/myapp/logs/application.log}
#    level:
#      root: INFO
#      com:
#        website:
#          campaings:
#            banner_project: DEBUG
#    pattern:
#      console: %d{yyyy-MM-dd HH:mm:ss} - %msg%n
#      file: %d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
